import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src'))
from database.models import init_db, add_word

def populate_words():
    """Заполнение базы данных словами"""
    
    # Инициализация базы данных
    init_db()
    
    # Слова для уровня A1 (50 слов)
    a1_words = [
        ("hello", "[həˈloʊ]", "привет", "Hello, how are you?", "A1"),
        ("goodbye", "[ˌɡʊdˈbaɪ]", "до свидания", "Goodbye, see you later!", "A1"),
        ("yes", "[jes]", "да", "Yes, I understand.", "A1"),
        ("no", "[noʊ]", "нет", "No, I don't know.", "A1"),
        ("please", "[pliːz]", "пожалуйста", "Please help me.", "A1"),
        ("thank you", "[ˈθæŋk juː]", "спасибо", "Thank you very much.", "A1"),
        ("sorry", "[ˈsɒri]", "извините", "I'm sorry for the mistake.", "A1"),
        ("excuse me", "[ɪkˈskjuːz miː]", "извините", "Excuse me, where is the station?", "A1"),
        ("water", "[ˈwɔːtər]", "вода", "I need some water.", "A1"),
        ("food", "[fuːd]", "еда", "The food is delicious.", "A1"),
        ("house", "[haʊs]", "дом", "This is my house.", "A1"),
        ("car", "[kɑːr]", "машина", "I drive a car.", "A1"),
        ("book", "[bʊk]", "книга", "I read a book.", "A1"),
        ("pen", "[pen]", "ручка", "Can I borrow your pen?", "A1"),
        ("table", "[ˈteɪbl]", "стол", "Put the book on the table.", "A1"),
        ("chair", "[tʃeər]", "стул", "Sit on the chair.", "A1"),
        ("door", "[dɔːr]", "дверь", "Close the door, please.", "A1"),
        ("window", "[ˈwɪndoʊ]", "окно", "Open the window.", "A1"),
        ("phone", "[foʊn]", "телефон", "My phone is ringing.", "A1"),
        ("computer", "[kəmˈpjuːtər]", "компьютер", "I work on my computer.", "A1"),
        ("time", "[taɪm]", "время", "What time is it?", "A1"),
        ("day", "[deɪ]", "день", "Have a nice day!", "A1"),
        ("night", "[naɪt]", "ночь", "Good night!", "A1"),
        ("morning", "[ˈmɔːrnɪŋ]", "утро", "Good morning!", "A1"),
        ("evening", "[ˈiːvnɪŋ]", "вечер", "Good evening!", "A1"),
        ("today", "[təˈdeɪ]", "сегодня", "What are you doing today?", "A1"),
        ("tomorrow", "[təˈmɒroʊ]", "завтра", "See you tomorrow!", "A1"),
        ("yesterday", "[ˈjestərdeɪ]", "вчера", "I was busy yesterday.", "A1"),
        ("week", "[wiːk]", "неделя", "I work five days a week.", "A1"),
        ("month", "[mʌnθ]", "месяц", "Next month I'm going on vacation.", "A1"),
        ("year", "[jɪər]", "год", "Happy New Year!", "A1"),
        ("family", "[ˈfæmɪli]", "семья", "I love my family.", "A1"),
        ("mother", "[ˈmʌðər]", "мама", "My mother is cooking.", "A1"),
        ("father", "[ˈfɑːðər]", "папа", "My father is working.", "A1"),
        ("sister", "[ˈsɪstər]", "сестра", "I have a sister.", "A1"),
        ("brother", "[ˈbrʌðər]", "брат", "My brother is older than me.", "A1"),
        ("friend", "[frend]", "друг", "She is my best friend.", "A1"),
        ("teacher", "[ˈtiːtʃər]", "учитель", "My teacher is very kind.", "A1"),
        ("student", "[ˈstjuːdnt]", "студент", "I am a student.", "A1"),
        ("work", "[wɜːrk]", "работа", "I work in an office.", "A1"),
        ("study", "[ˈstʌdi]", "учеба", "I study English.", "A1"),
        ("learn", "[lɜːrn]", "учиться", "I want to learn Spanish.", "A1"),
        ("speak", "[spiːk]", "говорить", "I speak English.", "A1"),
        ("listen", "[ˈlɪsn]", "слушать", "Listen to the music.", "A1"),
        ("read", "[riːd]", "читать", "I read books.", "A1"),
        ("write", "[raɪt]", "писать", "I write emails.", "A1"),
        ("see", "[siː]", "видеть", "I can see the mountains.", "A1"),
        ("hear", "[hɪər]", "слышать", "I can hear the birds.", "A1"),
        ("know", "[noʊ]", "знать", "I know the answer.", "A1"),
        ("think", "[θɪŋk]", "думать", "I think it's a good idea.", "A1"),
        ("want", "[wɒnt]", "хотеть", "I want to travel.", "A1"),
        ("need", "[niːd]", "нуждаться", "I need some help.", "A1"),
        ("like", "[laɪk]", "нравиться", "I like this movie.", "A1"),
        ("love", "[lʌv]", "любить", "I love chocolate.", "A1"),
        ("big", "[bɪɡ]", "большой", "This is a big house.", "A1"),
        ("small", "[smɔːl]", "маленький", "I have a small car.", "A1"),
        ("good", "[ɡʊd]", "хороший", "This is a good book.", "A1"),
        ("bad", "[bæd]", "плохой", "The weather is bad today.", "A1"),
        ("new", "[njuː]", "новый", "I bought a new phone.", "A1"),
        ("old", "[oʊld]", "старый", "This is an old building.", "A1"),
        ("hot", "[hɒt]", "горячий", "The coffee is hot.", "A1"),
        ("cold", "[koʊld]", "холодный", "The water is cold.", "A1"),
        ("beautiful", "[ˈbjuːtɪfl]", "красивый", "She is beautiful.", "A1"),
        ("ugly", "[ˈʌɡli]", "уродливый", "This is an ugly picture.", "A1"),
        ("happy", "[ˈhæpi]", "счастливый", "I am happy today.", "A1"),
        ("sad", "[sæd]", "грустный", "Why are you sad?", "A1"),
        ("tired", "[ˈtaɪərd]", "уставший", "I am tired after work.", "A1"),
        ("hungry", "[ˈhʌŋɡri]", "голодный", "I am hungry.", "A1"),
        ("thirsty", "[ˈθɜːrsti]", "жаждущий", "I am thirsty.", "A1"),
    ]
    
    # Слова для уровня A2 (50 слов)
    a2_words = [
        ("adventure", "[ədˈventʃər]", "приключение", "We had an amazing adventure.", "A2"),
        ("business", "[ˈbɪznəs]", "бизнес", "He works in business.", "A2"),
        ("challenge", "[ˈtʃælɪndʒ]", "вызов", "This is a big challenge.", "A2"),
        ("decision", "[dɪˈsɪʒn]", "решение", "I made a difficult decision.", "A2"),
        ("experience", "[ɪkˈspɪəriəns]", "опыт", "She has a lot of experience.", "A2"),
        ("freedom", "[ˈfriːdəm]", "свобода", "Freedom is important.", "A2"),
        ("government", "[ˈɡʌvənmənt]", "правительство", "The government made a new law.", "A2"),
        ("happiness", "[ˈhæpinəs]", "счастье", "Money doesn't bring happiness.", "A2"),
        ("information", "[ˌɪnfərˈmeɪʃn]", "информация", "I need more information.", "A2"),
        ("knowledge", "[ˈnɒlɪdʒ]", "знание", "Knowledge is power.", "A2"),
        ("language", "[ˈlæŋɡwɪdʒ]", "язык", "English is a difficult language.", "A2"),
        ("medicine", "[ˈmedsn]", "медицина", "Modern medicine is very advanced.", "A2"),
        ("neighbor", "[ˈneɪbər]", "сосед", "My neighbor is very friendly.", "A2"),
        ("opportunity", "[ˌɒpəˈtjuːnəti]", "возможность", "This is a great opportunity.", "A2"),
        ("population", "[ˌpɒpjuˈleɪʃn]", "население", "The population is growing.", "A2"),
        ("question", "[ˈkwestʃən]", "вопрос", "I have a question for you.", "A2"),
        ("relationship", "[rɪˈleɪʃnʃɪp]", "отношения", "They have a good relationship.", "A2"),
        ("situation", "[ˌsɪtʃuˈeɪʃn]", "ситуация", "This is a difficult situation.", "A2"),
        ("technology", "[tekˈnɒlədʒi]", "технология", "Technology changes quickly.", "A2"),
        ("university", "[ˌjuːnɪˈvɜːsəti]", "университет", "I study at university.", "A2"),
        ("vacation", "[vəˈkeɪʃn]", "отпуск", "I'm going on vacation next week.", "A2"),
        ("weather", "[ˈweðər]", "погода", "The weather is nice today.", "A2"),
        ("exercise", "[ˈeksəsaɪz]", "упражнение", "Exercise is good for health.", "A2"),
        ("education", "[ˌedʒuˈkeɪʃn]", "образование", "Education is very important.", "A2"),
        ("environment", "[ɪnˈvaɪrənmənt]", "окружающая среда", "We must protect the environment.", "A2"),
        ("generation", "[ˌdʒenəˈreɪʃn]", "поколение", "Younger generation uses technology.", "A2"),
        ("imagination", "[ɪˌmædʒɪˈneɪʃn]", "воображение", "Children have great imagination.", "A2"),
        ("journey", "[ˈdʒɜːni]", "путешествие", "The journey was long.", "A2"),
        ("kitchen", "[ˈkɪtʃɪn]", "кухня", "I'm cooking in the kitchen.", "A2"),
        ("library", "[ˈlaɪbrəri]", "библиотека", "I study in the library.", "A2"),
        ("magazine", "[ˌmæɡəˈziːn]", "журнал", "I read this magazine.", "A2"),
        ("newspaper", "[ˈnjuːzpeɪpər]", "газета", "I read the newspaper every morning.", "A2"),
        ("office", "[ˈɒfɪs]", "офис", "I work in an office.", "A2"),
        ("passport", "[ˈpɑːspɔːt]", "паспорт", "I need my passport to travel.", "A2"),
        ("restaurant", "[ˈrestrɒnt]", "ресторан", "Let's go to a restaurant.", "A2"),
        ("schedule", "[ˈʃedjuːl]", "расписание", "I have a busy schedule.", "A2"),
        ("telephone", "[ˈtelɪfoʊn]", "телефон", "I'll call you on the telephone.", "A2"),
        ("umbrella", "[ʌmˈbrelə]", "зонт", "Take an umbrella, it's raining.", "A2"),
        ("vegetable", "[ˈvedʒtəbl]", "овощ", "I eat vegetables every day.", "A2"),
        ("wonderful", "[ˈwʌndəfl]", "чудесный", "It was a wonderful day.", "A2"),
        ("excellent", "[ˈeksələnt]", "отличный", "The food was excellent.", "A2"),
        ("difficult", "[ˈdɪfɪkəlt]", "сложный", "This is a difficult task.", "A2"),
        ("important", "[ɪmˈpɔːtnt]", "важный", "This is very important.", "A2"),
        ("interesting", "[ˈɪntrəstɪŋ]", "интересный", "This book is very interesting.", "A2"),
        ("necessary", "[ˈnesəsəri]", "необходимый", "It's necessary to study hard.", "A2"),
        ("possible", "[ˈpɒsəbl]", "возможный", "Is it possible to help me?", "A2"),
        ("different", "[ˈdɪfrənt]", "разный", "These are different colors.", "A2"),
        ("expensive", "[ɪkˈspensɪv]", "дорогой", "This car is very expensive.", "A2"),
        ("comfortable", "[ˈkʌmftəbl]", "удобный", "This chair is very comfortable.", "A2"),
        ("dangerous", "[ˈdeɪndʒərəs]", "опасный", "This is a dangerous place.", "A2"),
        ("famous", "[ˈfeɪməs]", "известный", "He is a famous actor.", "A2"),
        ("friendly", "[ˈfrendli]", "дружелюбный", "She is very friendly.", "A2"),
        ("healthy", "[ˈhelθi]", "здоровый", "Exercise keeps you healthy.", "A2"),
        ("modern", "[ˈmɒdn]", "современный", "This is a modern building.", "A2"),
        ("natural", "[ˈnætʃrəl]", "естественный", "This is natural beauty.", "A2"),
        ("personal", "[ˈpɜːsənl]", "личный", "This is my personal opinion.", "A2"),
        ("popular", "[ˈpɒpjələr]", "популярный", "This is a popular song.", "A2"),
        ("professional", "[prəˈfeʃənl]", "профессиональный", "He is a professional photographer.", "A2"),
        ("successful", "[səkˈsesfl]", "успешный", "She is a successful businesswoman.", "A2"),
        ("traditional", "[trəˈdɪʃənl]", "традиционный", "This is a traditional recipe.", "A2"),
        ("useful", "[ˈjuːsfl]", "полезный", "This information is very useful.", "A2"),
        ("valuable", "[ˈvæljuəbl]", "ценный", "This is a valuable lesson.", "A2"),
    ]
    
    # Слова для уровня B1 (50 слов)
    b1_words = [
        ("accomplish", "[əˈkʌmplɪʃ]", "выполнять", "I want to accomplish my goals.", "B1"),
        ("achieve", "[əˈtʃiːv]", "достигать", "She achieved great success.", "B1"),
        ("appreciate", "[əˈpriːʃieɪt]", "ценить", "I appreciate your help.", "B1"),
        ("approach", "[əˈproʊtʃ]", "подход", "This is a new approach to the problem.", "B1"),
        ("assume", "[əˈsjuːm]", "предполагать", "I assume you're busy.", "B1"),
        ("avoid", "[əˈvɔɪd]", "избегать", "Try to avoid mistakes.", "B1"),
        ("benefit", "[ˈbenɪfɪt]", "польза", "Exercise has many benefits.", "B1"),
        ("consider", "[kənˈsɪdər]", "рассматривать", "Please consider my proposal.", "B1"),
        ("consist", "[kənˈsɪst]", "состоять", "The team consists of five people.", "B1"),
        ("contain", "[kənˈteɪn]", "содержать", "This book contains useful information.", "B1"),
        ("contribute", "[kənˈtrɪbjuːt]", "вносить вклад", "Everyone can contribute to society.", "B1"),
        ("demonstrate", "[ˈdemənstreɪt]", "демонстрировать", "Let me demonstrate how it works.", "B1"),
        ("develop", "[dɪˈveləp]", "развивать", "We need to develop new skills.", "B1"),
        ("establish", "[ɪˈstæblɪʃ]", "устанавливать", "They established a new company.", "B1"),
        ("examine", "[ɪɡˈzæmɪn]", "исследовать", "Let's examine the evidence.", "B1"),
        ("experience", "[ɪkˈspɪəriəns]", "испытывать", "I experienced many difficulties.", "B1"),
        ("explain", "[ɪkˈspleɪn]", "объяснять", "Can you explain this to me?", "B1"),
        ("express", "[ɪkˈspres]", "выражать", "It's difficult to express my feelings.", "B1"),
        ("function", "[ˈfʌŋkʃn]", "функция", "This machine has many functions.", "B1"),
        ("generate", "[ˈdʒenəreɪt]", "генерировать", "The wind generates electricity.", "B1"),
        ("identify", "[aɪˈdentɪfaɪ]", "определять", "Can you identify the problem?", "B1"),
        ("improve", "[ɪmˈpruːv]", "улучшать", "I want to improve my English.", "B1"),
        ("indicate", "[ˈɪndɪkeɪt]", "указывать", "The signs indicate the way.", "B1"),
        ("maintain", "[meɪnˈteɪn]", "поддерживать", "It's important to maintain good health.", "B1"),
        ("obtain", "[əbˈteɪn]", "получать", "You need to obtain permission.", "B1"),
        ("occur", "[əˈkɜːr]", "происходить", "Accidents can occur anywhere.", "B1"),
        ("participate", "[pɑːˈtɪsɪpeɪt]", "участвовать", "I want to participate in the event.", "B1"),
        ("perform", "[pəˈfɔːm]", "выполнять", "She performs her duties well.", "B1"),
        ("prepare", "[prɪˈpeər]", "готовить", "I need to prepare for the exam.", "B1"),
        ("prevent", "[prɪˈvent]", "предотвращать", "We must prevent accidents.", "B1"),
        ("produce", "[prəˈdjuːs]", "производить", "This factory produces cars.", "B1"),
        ("provide", "[prəˈvaɪd]", "обеспечивать", "The school provides education.", "B1"),
        ("publish", "[ˈpʌblɪʃ]", "публиковать", "They publish books every year.", "B1"),
        ("recognize", "[ˈrekəɡnaɪz]", "узнавать", "I recognize this place.", "B1"),
        ("reduce", "[rɪˈdjuːs]", "уменьшать", "We need to reduce pollution.", "B1"),
        ("reflect", "[rɪˈflekt]", "отражать", "This decision reflects our values.", "B1"),
        ("require", "[rɪˈkwaɪər]", "требовать", "This job requires experience.", "B1"),
        ("respond", "[rɪˈspɒnd]", "отвечать", "Please respond to my email.", "B1"),
        ("reveal", "[rɪˈviːl]", "раскрывать", "The investigation revealed the truth.", "B1"),
        ("select", "[sɪˈlekt]", "выбирать", "Please select your preferred option.", "B1"),
        ("separate", "[ˈsepəreɪt]", "отделять", "We need to separate these items.", "B1"),
        ("significant", "[sɪɡˈnɪfɪkənt]", "значительный", "This is a significant change.", "B1"),
        ("similar", "[ˈsɪmɪlər]", "похожий", "These two things are very similar.", "B1"),
        ("specific", "[spəˈsɪfɪk]", "конкретный", "I need specific information.", "B1"),
        ("sufficient", "[səˈfɪʃnt]", "достаточный", "This amount is sufficient.", "B1"),
        ("suitable", "[ˈsuːtəbl]", "подходящий", "This is a suitable solution.", "B1"),
        ("various", "[ˈveəriəs]", "различный", "There are various options available.", "B1"),
        ("appropriate", "[əˈproʊpriət]", "подходящий", "This is an appropriate response.", "B1"),
        ("available", "[əˈveɪləbl]", "доступный", "This product is available now.", "B1"),
        ("capable", "[ˈkeɪpəbl]", "способный", "She is capable of great things.", "B1"),
        ("confident", "[ˈkɒnfɪdənt]", "уверенный", "I feel confident about this.", "B1"),
        ("efficient", "[ɪˈfɪʃnt]", "эффективный", "This is an efficient method.", "B1"),
        ("essential", "[ɪˈsenʃl]", "существенный", "This is essential information.", "B1"),
        ("familiar", "[fəˈmɪliər]", "знакомый", "This place looks familiar.", "B1"),
        ("frequent", "[ˈfriːkwənt]", "частый", "I make frequent visits.", "B1"),
        ("independent", "[ˌɪndɪˈpendənt]", "независимый", "She is very independent.", "B1"),
        ("obvious", "[ˈɒbviəs]", "очевидный", "The answer is obvious.", "B1"),
        ("positive", "[ˈpɒzətɪv]", "положительный", "I have a positive attitude.", "B1"),
        ("previous", "[ˈpriːviəs]", "предыдущий", "In the previous chapter.", "B1"),
        ("recent", "[ˈriːsnt]", "недавний", "This is a recent development.", "B1"),
        ("responsible", "[rɪˈspɒnsəbl]", "ответственный", "You must be responsible.", "B1"),
        ("serious", "[ˈsɪəriəs]", "серьезный", "This is a serious problem.", "B1"),
        ("successful", "[səkˈsesfl]", "успешный", "The project was successful.", "B1"),
        ("typical", "[ˈtɪpɪkl]", "типичный", "This is a typical example.", "B1"),
        ("unusual", "[ʌnˈjuːʒuəl]", "необычный", "This is an unusual situation.", "B1"),
        ("valuable", "[ˈvæljuəbl]", "ценный", "This is valuable advice.", "B1"),
    ]
    
    # Слова для уровня B2 (50 слов)
    b2_words = [
        ("accomplishment", "[əˈkʌmplɪʃmənt]", "достижение", "This is a great accomplishment.", "B2"),
        ("acknowledge", "[əkˈnɒlɪdʒ]", "признавать", "I acknowledge your contribution.", "B2"),
        ("acquire", "[əˈkwaɪər]", "приобретать", "She acquired new skills quickly.", "B2"),
        ("adequate", "[ˈædɪkwət]", "адекватный", "The response was adequate.", "B2"),
        ("adjust", "[əˈdʒʌst]", "приспосабливаться", "You need to adjust to the new situation.", "B2"),
        ("alternative", "[ɔːlˈtɜːnətɪv]", "альтернатива", "We need to find an alternative.", "B2"),
        ("appropriate", "[əˈproʊpriət]", "соответствующий", "This is an appropriate solution.", "B2"),
        ("assume", "[əˈsjuːm]", "предполагать", "I assume you understand.", "B2"),
        ("authority", "[ɔːˈθɒrəti]", "власть", "He has authority in this matter.", "B2"),
        ("available", "[əˈveɪləbl]", "доступный", "The information is available online.", "B2"),
        ("benefit", "[ˈbenɪfɪt]", "выгода", "This will benefit everyone.", "B2"),
        ("capable", "[ˈkeɪpəbl]", "способный", "She is capable of leadership.", "B2"),
        ("capacity", "[kəˈpæsəti]", "способность", "He has the capacity to learn.", "B2"),
        ("circumstance", "[ˈsɜːkəmstəns]", "обстоятельство", "Under these circumstances.", "B2"),
        ("comment", "[ˈkɒment]", "комментарий", "I have no comment on this.", "B2"),
        ("concentrate", "[ˈkɒnsntreɪt]", "концентрироваться", "Please concentrate on your work.", "B2"),
        ("conclude", "[kənˈkluːd]", "заключать", "I conclude that this is correct.", "B2"),
        ("considerable", "[kənˈsɪdərəbl]", "значительный", "This requires considerable effort.", "B2"),
        ("consist", "[kənˈsɪst]", "состоять", "The team consists of experts.", "B2"),
        ("constant", "[ˈkɒnstənt]", "постоянный", "There is constant change.", "B2"),
        ("construct", "[kənˈstrʌkt]", "строить", "They construct buildings.", "B2"),
        ("contain", "[kənˈteɪn]", "содержать", "This book contains valuable information.", "B2"),
        ("contribute", "[kənˈtrɪbjuːt]", "способствовать", "This contributes to success.", "B2"),
        ("convince", "[kənˈvɪns]", "убеждать", "I need to convince them.", "B2"),
        ("correspond", "[ˌkɒrəˈspɒnd]", "соответствовать", "This corresponds to our needs.", "B2"),
        ("demonstrate", "[ˈdemənstreɪt]", "демонстрировать", "This demonstrates the problem.", "B2"),
        ("derive", "[dɪˈraɪv]", "получать", "We derive benefits from this.", "B2"),
        ("determine", "[dɪˈtɜːmɪn]", "определять", "We need to determine the cause.", "B2"),
        ("develop", "[dɪˈveləp]", "развивать", "We develop new technologies.", "B2"),
        ("distinguish", "[dɪˈstɪŋɡwɪʃ]", "различать", "It's hard to distinguish them.", "B2"),
        ("establish", "[ɪˈstæblɪʃ]", "устанавливать", "We establish new rules.", "B2"),
        ("evaluate", "[ɪˈvæljueɪt]", "оценивать", "We need to evaluate the results.", "B2"),
        ("examine", "[ɪɡˈzæmɪn]", "исследовать", "Let's examine the evidence.", "B2"),
        ("exhibit", "[ɪɡˈzɪbɪt]", "выставлять", "The museum exhibits art.", "B2"),
        ("expand", "[ɪkˈspænd]", "расширять", "The company expands rapidly.", "B2"),
        ("explore", "[ɪkˈsplɔːr]", "исследовать", "We explore new possibilities.", "B2"),
        ("express", "[ɪkˈspres]", "выражать", "I express my opinion clearly.", "B2"),
        ("extend", "[ɪkˈstend]", "расширять", "We extend our services.", "B2"),
        ("facilitate", "[fəˈsɪlɪteɪt]", "облегчать", "This facilitates learning.", "B2"),
        ("generate", "[ˈdʒenəreɪt]", "генерировать", "This generates income.", "B2"),
        ("identify", "[aɪˈdentɪfaɪ]", "определять", "We identify the problems.", "B2"),
        ("illustrate", "[ˈɪləstreɪt]", "иллюстрировать", "This illustrates the point.", "B2"),
        ("implement", "[ˈɪmplɪment]", "внедрять", "We implement new policies.", "B2"),
        ("indicate", "[ˈɪndɪkeɪt]", "указывать", "This indicates progress.", "B2"),
        ("interpret", "[ɪnˈtɜːprɪt]", "интерпретировать", "How do you interpret this?", "B2"),
        ("maintain", "[meɪnˈteɪn]", "поддерживать", "We maintain high standards.", "B2"),
        ("obtain", "[əbˈteɪn]", "получать", "We obtain the necessary data.", "B2"),
        ("participate", "[pɑːˈtɪsɪpeɪt]", "участвовать", "Everyone can participate.", "B2"),
        ("perceive", "[pəˈsiːv]", "воспринимать", "How do you perceive this?", "B2"),
        ("perform", "[pəˈfɔːm]", "выполнять", "They perform their duties.", "B2"),
        ("preserve", "[prɪˈzɜːv]", "сохранять", "We preserve our traditions.", "B2"),
        ("proceed", "[prəˈsiːd]", "продолжать", "We proceed with the plan.", "B2"),
        ("promote", "[prəˈmoʊt]", "продвигать", "We promote innovation.", "B2"),
        ("pursue", "[pəˈsjuː]", "преследовать", "We pursue our goals.", "B2"),
        ("recognize", "[ˈrekəɡnaɪz]", "узнавать", "We recognize the importance.", "B2"),
        ("reflect", "[rɪˈflekt]", "отражать", "This reflects our values.", "B2"),
        ("regard", "[rɪˈɡɑːd]", "рассматривать", "We regard this as important.", "B2"),
        ("release", "[rɪˈliːs]", "выпускать", "We release new products.", "B2"),
        ("require", "[rɪˈkwaɪər]", "требовать", "This requires attention.", "B2"),
        ("resolve", "[rɪˈzɒlv]", "решать", "We resolve conflicts.", "B2"),
        ("reveal", "[rɪˈviːl]", "раскрывать", "This reveals the truth.", "B2"),
        ("specify", "[ˈspesɪfaɪ]", "указывать", "Please specify the details.", "B2"),
        ("sufficient", "[səˈfɪʃnt]", "достаточный", "This is sufficient evidence.", "B2"),
        ("undertake", "[ˌʌndəˈteɪk]", "предпринимать", "We undertake new projects.", "B2"),
        ("utilize", "[ˈjuːtəlaɪz]", "использовать", "We utilize resources efficiently.", "B2"),
        ("vary", "[ˈveəri]", "варьироваться", "Prices vary significantly.", "B2"),
    ]
    
    # Добавляем все слова в базу данных
    all_words = a1_words + a2_words + b1_words + b2_words
    
    print("Начинаю заполнение базы данных словами...")
    
    for word_data in all_words:
        word, transcription, translation, example, level = word_data
        add_word(word, transcription, translation, example, level)
        print(f"Добавлено слово: {word} ({level})")
    
    print(f"\nБаза данных заполнена! Добавлено {len(all_words)} слов:")
    print(f"- A1: {len(a1_words)} слов")
    print(f"- A2: {len(a2_words)} слов")
    print(f"- B1: {len(b1_words)} слов")
    print(f"- B2: {len(b2_words)} слов")

if __name__ == "__main__":
    populate_words() 